name: test-with-pixi

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches:
      - "*"
      - "!gh-pages"
  schedule:
    - cron: "0 4 * * MON"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        os: ["ubuntu-latest"]
        rdkit-version: ["2023.09"]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    defaults:
      run:
        shell: pixi run bash {0}

    name: |
      os=${{ matrix.os }}
      - python=${{ matrix.python-version }}
      - rdkit=${{ matrix.rdkit-version }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
